### ISSUE TITLE
Try Traefik

### ISSUE THREAD

**Issue by daviddwlee84** [daviddwlee84/Nginx-DockerCompose#1]
- [Traefik, The Cloud Native Application Proxy | Traefik Labs](https://traefik.io/traefik/)
- [traefik/traefik: The Cloud Native Application Proxy](https://github.com/traefik/traefik)

---

Example

- [Docker — Glances 3.4.0.3 documentation](https://glances.readthedocs.io/en/latest/docker.html)

```yaml
services:
  reverse-proxy:
    image: traefik:alpine
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  monitoring:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    labels:
      - "traefik.port=61208"
      - "traefik.frontend.rule=Host:glances.docker.localhost"
```

---

- [Choosing the Right Tool: A Detailed Traefik vs. Nginx Showdown - BestCloudPlatform](https://bestcloudplatform.com/choosing-the-right-tool-a-detailed-traefik-vs-nginx-showdown/)
